Lower elemental user defined assignment
flang-compiler/f18-llvm-project pull request #1086
Opened 2021-09-23 19:33 UTC by jeanPerier

**1. Introduce a new fir.array_modify to decorrelate the identification of the assignment from its semantics**

fir.array_update is only handling intrinsic assignments.
They are two big differences with user defined assignments:
- The LHS and RHS types may not match, this does not play well
   with fir.array_update that relies on both the merge and the
   updated element to have the same type.
- User defined assignment has a call semantics, with potential
   side effects. So if a fir.array_update can hide a call, it traits
   would need to be updated.

Instead of hiding more semantic in the fir.array_update, introduce
a new fir.array_modify op that allows de-correlating indicating that
an array value element is modified, and how it is modified.
This allow the ArrayValueCopy pass to still perform copy elision
while not having to implement the call itself, and could in general
be used for all kind of assignments (e.g. character assignment).

Note that fir.array_modify still has a merge argument that is not used to generate anything but is central for the ArrayValueCopy alias analysis (see populateSets in ArrayValueCopy.cpp).

**2. Update Lowering to use it and lower user defined assignment in elemental contexts**

Note: user assignments involving characters need a bit more work because the RHS length is not tracked currently at the place where array_update are generated. Elemental user defined assignment Where and Forall are also not yet handled.

2021-09-24 12:16 UTC, clementval approved these changes
As I mentioned before, I probably do not have the full picture ywt but overall it looks good to me. 

You might want to add a small test in `flang/test/Fir/invalid.fir` so we check the errors emitted by the verifier.

2021-09-24 15:29 UTC, schweitzpgi requested changes

2021-09-24 17:19 UTC, jeanPerier commented on flang/lib/Lower/ConvertExpr.cpp
> +      auto prepareUserDefinedArg = [](fir::FirOpBuilder &builder,
OK, I'll try that. 
> and that should be done by adding and changing a new semantics type when traversing the lhs expression.

Just to check, you mean to add a new ConstituentSemantics option to generate the fir.array_modify ?

2021-09-27 14:10 UTC, jeanPerier commented on flang/include/flang/Optimizer/Dialect/FIROps.td
> +      %addr, %r = fir.array_update %v, %rhs, %i, %j : (!fir.array<?x?xf32>, fir.ref<!fir.type<SomeType>>,  index, index) -> fir.ref<f32>, !fir.array<?x?xf32>
Fixed.

2021-09-27 14:10 UTC, jeanPerier commented on flang/include/flang/Optimizer/Dialect/FIROps.td
> +      fir.array_merge_store %v, %r to %a : !fir.ref<!fir.array<?x?xf32>>
Added a fir.do_loop here.

2021-09-27 14:10 UTC, jeanPerier commented on flang/include/flang/Optimizer/Dialect/FIROps.td
> +    AnyType:$merge,
OK, it was easier to not do that at first, but I have made an alias analysis update to remove the need of this Operand. See new commit https://github.com/flang-compiler/f18-llvm-project/pull/1086/commits/6cf579c2c50f41864956b9bcdc656f1d4dd16072.
I refactored the analysis in a ReachCollector class and the analysis is able to follow the direct and indirect operations using the result element address, and then to go back through the operands of these operations to find array accesses.

This also brings the need to be able to go through stores that may be done inside the loops to transform RHS values into something that can be passed to a user defined assignment function as an argument in memory.

2021-09-27 14:10 UTC, jeanPerier commented on flang/lib/Lower/ConvertExpr.cpp
> +      auto prepareUserDefinedArg = [](fir::FirOpBuilder &builder,
Updated in https://github.com/flang-compiler/f18-llvm-project/pull/1086/commits/6a3af7acbc64d19c888267cefb1567d3ede89525.
I added a new CustomCopyInCopyOut semantics that creates and return a fir.array_modifies, the actual elemental function calls is created in the ccStoreToDest in `lowerUserDefinedAssignment`.

Feel free to pick a better name than `CustomCopyInCopyOut`.

2021-09-28 12:22 UTC, jeanPerier commented
Rebased to solve conflicts.

2021-09-28 18:49 UTC, schweitzpgi commented on flang/lib/Lower/ConvertExpr.cpp
> +    // the destination length parameters are being tracked.
It looks like this is being called from a continuation in the evaluate loop. The IterationSpace ought to have a proper ExtendedValue for what the rhs was evaluated to be (`elementExv()`), which would include the LEN (modulo bugs). Also, it looks like the `lhs` argument is the `array_merge` operation, which should have been created with the appropriate type parameters properties. Is something else required?

2021-09-28 18:49 UTC, schweitzpgi commented on flang/include/flang/Optimizer/Dialect/FIROps.td
> +        fir.result %r : !fir.ref<!fir.array<?xf32>>
I'm a little worried about the threading of `%r` here. I think we want to capture that value after the call, so we may want to tweak this slightly.

2021-09-28 18:49 UTC, schweitzpgi commented on flang/lib/Lower/ConvertExpr.cpp
> +      }
nit: curlies.

2021-09-28 18:49 UTC, schweitzpgi commented on flang/lib/Optimizer/Dialect/FIROps.cpp
> +  if (indSize < arrTy.getDimension())
Should this be `!=`?

2021-09-28 18:49 UTC, schweitzpgi commented on flang/lib/Optimizer/Transforms/ArrayValueCopy.cpp
> +                                     const ArrayCopyAnalysis &a,
Makes sense.

2021-09-28 18:49 UTC, schweitzpgi commented on flang/lib/Optimizer/Transforms/ArrayValueCopy.cpp
> +namespace {
The github presentation of the diffs in this file is confusing. I'll take a look via the branch...

2021-09-28 19:28 UTC, schweitzpgi reviewed
Overall, this looks really good, Jean. Thanks for taking this on. I really appreciate your help here.

There are a couple of niggly things I'm not totally sure about, but otherwise well done.

2021-09-28 19:28 UTC, schweitzpgi commented on flang/lib/Optimizer/Transforms/ArrayValueCopy.cpp
> +  void collectValuesStoredTo(mlir::Operation *alloc) {}
This member function does not appear to be used.

2021-09-28 19:28 UTC, schweitzpgi commented on flang/lib/Optimizer/Transforms/ArrayValueCopy.cpp
> +namespace {
OK. With better tools, I can tell you're turning the recursive function into a class.

2021-09-28 19:28 UTC, schweitzpgi commented on flang/lib/Optimizer/Transforms/ArrayValueCopy.cpp
> +      if (mlir::isa<fir::AllocaOp, fir::AllocMemOp>(op))
I'm not totally clear as to why the look at these dynamic allocations was added here. The relevant scope should be from the dominating `array_loads` over the region to the post-dominating `array_merge_store`. Some questions arise: what about arrays that are not locally allocated? Does this discriminate scalars somehow? What happens if we reach an alloca of an array, but it is used in more than one copy-in/copy-out context?

2021-09-28 19:28 UTC, schweitzpgi commented on flang/lib/Optimizer/Transforms/ArrayValueCopy.cpp
> +            if (opIsInsideLoops(store))
Does this introduce a phase ordering between this pass and loop rewrites?

2021-09-28 19:28 UTC, schweitzpgi commented on flang/lib/Optimizer/Transforms/ArrayValueCopy.cpp
> +    loopRegion = &doLoop->getRegion(0);
Not sure about this new restriction (with the do_loop). We can discuss offline though.

2021-09-29 15:23 UTC, jeanPerier reviewed
Thanks for the review, I have updated the patch with the nits and character support.
Regarding the alias analysis change, let's discuss to agree on a way forward.

2021-09-29 17:11 UTC, schweitzpgi commented on flang/include/flang/Optimizer/Dialect/FIROps.td
> +        fir.result %r : !fir.ref<!fir.array<?xf32>>
Yes, it is the theoretical point I was concerned about. (I had the same "fix" in mind here, btw.)

Like you, I'm not sure it matters too much for the moment...

2021-09-29 18:35 UTC, schweitzpgi approved these changes

2021-09-30 11:52 UTC, merged