[flang] Add lowering stubs for OpenMP/OpenACC declarative construct in module
flang-compiler/f18-llvm-project pull request #1184
Opened 2021-11-02 10:53 UTC by PeixinQiao

The OpenMP/OpenACC declarative construct can be declared in module declaration scope. This patch adds interface for lowering it.

2021-11-03 14:38 UTC, PeixinQiao commented on flang/test/Lower/OpenMP/omp-threadprivate.f90
>  ! RUN:   FileCheck %s --check-prefix=FIRDialect
This is only a stub.
```
// Without this patch
$ bbc -fopenmp -emit-fir case.f90 
bbc: /home/.../f18-llvm-project/flang/lib/Lower/PFTBuilder.cpp:369: Fortran::lower::pft::Evaluation& {anonymous}::PFTBuilder::addEvaluation(Fortran::lower::pft::Evaluation&&): Assertion `!evaluationListStack.empty() && "empty evaluation list stack"' failed.
// With this patch
$ bbc -fopenmp -emit-fir case.f90 
error: loc("./case.f90":1:1): /home/.../f18-llvm-project/flang/lib/Lower/OpenMP.cpp:712: not yet implemented OpenMPThreadprivate
LLVM ERROR: aborting
```

2022-01-13 18:46 UTC, schweitzpgi requested changes
Conflicts need to be resolved.

2022-01-14 09:39 UTC, PeixinQiao commented
@schweitzpgi Thanks for the notice. Addressed the conflicts.

2022-01-25 19:59 UTC, schweitzpgi approved these changes

2022-01-25 19:59 UTC, schweitzpgi commented
@kiranchandramohan Are you ok with this one?

2022-01-25 21:51 UTC, kiranchandramohan approved these changes
LGTM.
OK with me @schweitzpgi

2022-01-25 22:06 UTC, merged