Draft of style guidelines.
flang-compiler/f18-llvm-project pull request #1189
Opened 2021-11-02 19:17 UTC by schweitzpgi

Update comments to point to flang/llvm style document.

2021-11-02 20:14 UTC, psteinfeld requested changes

2021-11-02 20:59 UTC, schweitzpgi commented on flang/docs/LLVMCodingStyle.md
> +decision was made to adopt the MLIR style and coding conventions. The
Flang has multiple coding conventions though.

2021-11-02 21:06 UTC, psteinfeld commented on flang/docs/LLVMCodingStyle.md
> +decision was made to adopt the MLIR style and coding conventions. The
> 
> 
> Flang has multiple coding conventions though.
To be clear, here's what I recommend:
`In the directories that deal extensively with MLIR and LLVM, Flang uses the MLIR style and coding conventions.`

2021-11-02 21:47 UTC, psteinfeld approved these changes
Looks great!

Ship it.

2021-11-03 07:48 UTC, jeanPerier approved these changes

2021-11-03 12:08 UTC, banach-space commented
This is a divergence from LLVM's coding style and I feel that it should be discussed with the wider community first. Unless this is to remain a `fir-dev` specific change? But IIUC, all of `fir-dev` is to be moved to LLVM's `main`.

2021-11-03 12:09 UTC, clementval commented
> This is a divergence from LLVM's coding style and I feel that it should be discussed with the wider community first. Unless this is to remain a `fir-dev` specific change? But IIUC, all of `fir-dev` is to be moved to LLVM's `main`.

The LLVM coding style is not very clear on this (at least it is how I read it) and we are not saying use `auto` everywhere all the time. Anyway this will be probably be discussed when pushing this upstreaming in the phabricator patch.

2021-11-03 16:28 UTC, clementval approved these changes

2021-11-03 17:02 UTC, banach-space commented
> @banach-space The LLVM coding style is not very clear on this (at least it is how I read it)

That's why I think it is important to involve people who wrote the original guidelines (or participated in that discussion).

> Anyway this will be probably be discussed when pushing this upstreaming in the phabricator patch.

Why not create this PR on Phabricator then? This is effectively increasing the `fir-dev` delta. Admittedly, not by much, but it does touch quite a few files. Also, we do know that there are developers actively reviewing Flang patches on Phabricator and who are interested in this conversation, but don't really visit here.

IMHO, it would make a lot of sense to send this directly to LLVM `main`.

2021-11-03 17:36 UTC, schweitzpgi commented
> > @banach-space The LLVM coding style is not very clear on this (at least it is how I read it)
> 
> That's why I think it is important to involve people who wrote the original guidelines (or participated in that discussion).
> 
> > Anyway this will be probably be discussed when pushing this upstreaming in the phabricator patch.
> 
> Why not create this PR on Phabricator then? This is effectively increasing the `fir-dev` delta. Admittedly, not by much, but it does touch quite a few files. Also, we do know that there are developers actively reviewing Flang patches on Phabricator and who are interested in this conversation, but don't really visit here.
> 
> IMHO, it would make a lot of sense to send this directly to LLVM `main`.

I agree that more discussion can be had on mailing lists and/or phabricator.

This documents what has been done. It clarifies the policy.

2021-11-03 22:38 UTC, closed without merging