Visit parse tree instead of scopes to identify captured variables
flang-compiler/f18-llvm-project pull request #1203
Opened 2021-11-08 16:57 UTC by jeanPerier

In the context of internal procedure, lowering was relying on scope
information to identify which symbols from a host procedure are used
inside the internal procedures. This relied on symbols with
semantics::HostAssocDetails to be created by the front end for all
such variables used inside internal procedures. This is not always
done, and would be hard to enforce in the frontend/ is not a feature
the front end needs.

Instead, this patch adds a parse tree visitor that calls a call back
on all symbols referenced in a parse-tree procedure node.

This visitor is used for internal procedure with a callback that uses
scopes to determine if a symbol is captured from the host.

This allows fixing issue 990 (statement functions inside internal
procedures hit symbol is symbol is not mapped assert).

This also allows fixing the assert/TODO hit when dummy procedure
symbols from the host are used in an internal procedure. For this
part, on top of detecting the symbol capture, a new CapturedProcedure
class is added in HostAssociations.cpp to defined how this capture
should be done.

2021-11-08 19:13 UTC, psteinfeld requested changes
After fixing the warning in .../flang/lib/Lower/PFTBuilder.cpp, all builds, tests, and looks good.

2021-11-08 19:13 UTC, psteinfeld commented on flang/lib/Lower/PFTBuilder.cpp
> +  };
I get a warning (and thus a build error) because this line has an unnecessary ";".

I'm using GNU 9.3.0 for my builds.

2021-11-08 23:40 UTC, schweitzpgi approved these changes
This fixes the expression rewrites I see in some of the tests that are resulting in host associated variables being exposed in internal subprograms when they are otherwise unreferenced.

2021-11-08 23:40 UTC, schweitzpgi commented on flang/test/Lower/host-associated.f90
> +  ! Test that captured symbols used only in statement functions
I think this really means "internal subprograms", right?

2021-11-09 14:55 UTC, jeanPerier reviewed
> I get a warning (and thus a build error) because this line has an unnecessary ";".

I'm using GNU 9.3.0 for my builds.

Thanks Pete, I removed those.

2021-11-09 16:01 UTC, merged