Use fir.ptr to denote that equivalenced variables are aliases in FIR
flang-compiler/f18-llvm-project pull request #1254
Opened 2021-11-19 15:04 UTC by jeanPerier

ArrayValueCopy pass was doing a copy elision on assignment involving
overlapping equivalenced variables. Use fir.ptr type when instantiating
equivalenced variables to indicate that they are aliases to FIR.

2021-11-19 16:24 UTC, psteinfeld approved these changes
All builds, tests, and looks good.

2021-11-19 17:13 UTC, schweitzpgi requested changes
This does not follow from the semantics of the `!fir.ptr` type.

EQUIVALENCEd variables map to the same aggregate storage variable. The original names of the variables do not apply in terms of alias analysis then, since all EQUIVALENCEd variables are for alias purposes the same aggregate.

Backdooring these as POINTER variables confuses them with actual POINTERs and TARGETs and will make improving alias analysis more difficult.

2021-11-22 10:25 UTC, jeanPerier commented
> This does not follow from the semantics of the `!fir.ptr` type.
> 
> EQUIVALENCEd variables map to the same aggregate storage variable. The original names of the variables do not apply in terms of alias analysis then, since all EQUIVALENCEd variables are for alias purposes the same aggregate.
> 
> Backdooring these as POINTER variables confuses them with actual POINTERs and TARGETs and will make improving alias analysis more difficult.

OK. Is this an array value copy pass issue then ?

2021-11-22 22:37 UTC, schweitzpgi commented
> OK. Is this an array value copy pass issue then ?

Yes and no. The alias analysis in array value copy does not deal with equivalence aliasing currently. So that needs to be implemented.

It is also a lowering issue. Equivalence aliasing can be presented through association, and that is also not implemented.

2021-11-23 17:28 UTC, jeanPerier commented
Centralized the code casting equivalenced variable address to fir.ptr and left a TODO in the code so that we can track performance issue introduced by this PR.

2021-11-23 19:10 UTC, schweitzpgi approved these changes

2021-11-24 09:11 UTC, merged