The front end was folding away a function call that was an argument to
flang-compiler/f18-llvm-project pull request #1432
Opened 2022-02-01 20:10 UTC by schweitzpgi

the LEN intrinsic even when the result of the function call was not a
constant. This left LEN(func-name) in the expression which has no
semantics as the function had to be called with an argument to get the
return value's LEN property at runtime.

Update test to remove fir.convert.

2022-02-01 21:42 UTC, psteinfeld requested changes
The changes look good, but when I try to build it, I get errors in ld:

undefined reference to `bool Fortran::evaluate::IsConstantExpr<std::optional<Fortran::evaluate::Expr<Fortran::evaluate::Type<(Fortran::common::TypeCategory)0, 8> > > >(std::optional<Fortran::evaluate::Expr<Fortran::evaluate::Type<(Fortran::common::TypeCategory)0, 8> > > const&)'

2022-02-01 22:19 UTC, schweitzpgi commented
> The changes look good, but when I try to build it, I get errors in ld:
> 
> undefined reference to `bool Fortran::evaluate::IsConstantExpr<std::optional<Fortran::evaluate::Expr<Fortran::evaluate::Type<(Fortran::common::TypeCategory)0, 8> > > >(std::optional<Fortran::evaluate::Expr<Fortran::evaluate::Type<(Fortran::common::TypeCategory)0, 8> > > const&)'

Strange. Thanks for the heads-up. I'll look into it.

2022-02-01 22:53 UTC, psteinfeld approved these changes
Latest version looks good.

2022-02-02 01:53 UTC, merged

2022-02-03 17:16 UTC, klausler commented
The predicate is too strong.  It's going to prevent folding of things like LEN(X(1:5)) to 5.