lower runtime type info as linkonce objects in all compilation units
flang-compiler/f18-llvm-project pull request #1510
Opened 2022-03-02 11:29 UTC by jeanPerier

Note: The first two commits are modifying the front-end/codegen and are directly up for review in LLVM ([D120804](https://reviews.llvm.org/D120804) and [D120801](https://reviews.llvm.org/D120801)), only the last commit about lowering is up for review here (the first commits are required to get end-to-end tests to pass).

A number of issues were caused by derived type descriptors not being
generated as expected, and the issues being only caught at compile time.

This changes ensures lowering will generate runtime type info for all
the derived types that have been seen (converted) in lowering, instead
of relying on the runtime type info to be generated.
The runtime type info will also always be fully defined, even if the
type is not owned by the current compilation unit (e.g. defined in an
external module). To allow this to work without any conflict, the
`linkonce` LLVM linkage will be used. This allows same runtime type info
from different compilation units to be merged at linktime. The property
that a derived type descriptor address uniquely identifies a type will
thus still hold true.

The main motivation of this change is to allow KIND parameterized
derived type to work properly. The derived type descriptor of KIND
parametrized derived type can only be built during the type instantiation.
If the previous approach was kept, this could lead to "diamond" conflicts
if the same kind instantiation of a kind parametrized type defined in a
module A were done in modules B and C, and that a program P used both B and C.
The same runtime type info would be defined in B an C as external, and
caused link time errors when linking P. Using linkonce solves this
issue.

There are two other benefits to this change:
- It is no longer necessary to link against a module that defines
derived types only since the related type descriptors will be generated
by all compilation units that may use it.
- LLVM can safely discard unused runtime time info in the current
compilation unit since it is no longer necessary to retain it in case
another compilation unit might need it. This means that if no
compilation units turns out to need some module runtime type info, it
will just be thrown away by LLVM.

2022-03-02 11:59 UTC, sscalpone commented
What is the user-visible behavior when the user links incompatible out-of-date link-once sections?  (I'm hoping for an error from the linker to signal that the sections are not the same.)

Is data generated for all of the visible types or just the types that are used (+ closure)?

2022-03-02 13:32 UTC, jeanPerier commented
> What is the user-visible behavior when the user links incompatible out-of-date link-once sections? (I'm hoping for an error from the linker to signal that the sections are not the same.)

No because LLVM `linkonce` seems to be implemented with `weak` symbols where it is OK to provide conflicting definitions, and the first definition that get linked wins ([source](https://maskray.me/blog/2021-04-25-weak-symbol)). LLVM `linkonce_odr` might solve the issue since it claims to only merge "equivalent" globals, but I failed to find good documentation about how this is actually implemented. I can investigate that further.

> Is data generated for all of the visible types or just the types that are used (+ closure)?

Just the types that are used  (+closure). To be more precise, the front-end generates this data for all visible types, however, lowering will not lower runtime info from external modules if the types are not used in the current translation unit.

Let's take an example:

`mod.f90` defines two types `t1` and `t2`
```fortran
module mod
 type t1
  integer :: i
 end type 
 type t2
  real :: x
 end type
end module
```

`prog.f90` uses `mod` but only actually uses `t1`:

```
  use :: mod
  type(t1) :: some_t1
  print *, some_t1
end
```

When compiling `mod.f90`:
 - The front-end will generate runtime type info symbols for both `t1` and `t2`.
 - Lowering will lower this runtime type info since it belongs to the module scope currently being lowered.
 - LLVM optimization can drop this data since the symbols are actually not used in this compilation unit (`opt`, `clang -O1` and more get rid of it, `llc` will keep it). If there was any usages of the types in `mod.f90` that required making descriptors, they would have to be kept here.

When compiling `prog.f90`:
 - The front-end will generate runtime type info symbols for both `t1` and `t2`.
 - Lowering will only lower `t1` runtime type info since `t2` is visible but does not belong to the current compilation unit and does not appear in any part of the program touched by lowering.
 - LLVM must keep `t1` runtime type info because it is used  by the descriptor for the IO statement.

2022-03-02 13:55 UTC, jeanPerier commented
Re `linkonce_odr`: I tested, it will not allow detecting conflicting declaration at link time.
This is actually only a "guarantee" given by the LLVM that all definition are supposed to be the same, and that it can assumes the definition it sees should not legally be overridden by a different definition, which would be legal with `linkonce`.

It looks like using COMDATs could allow asking the linker to check that the data is equivalent with if the `ExactMatch` flag is set. However, according to [LLVM manual](https://llvm.org/docs/LangRef.html#comdats), COMDAT support in file format is low (ELF does  not support `ExactMatch`, XCOFF and Mach-O do not support COMDAT, only COFF seems to support it).
Also, I have no idea how to deal with COMDATs in MLIR.

So I do not have a good solution to prevent outdated runtime type info to be linked by mistake. It sounds to me that if a module is modified, all the files that use it should be recompiled, or there could be other weird errors anyway. But being able to complain if the linker sees incompatible definitions would have been nice.

2022-03-02 20:38 UTC, sscalpone commented
Thanks @jeanPerier.   Perhaps someday the linker or other tools will help the user find out-of-date information.  We don't have to solve that problem.

2022-03-09 08:54 UTC, jeanPerier commented
ping (Both LLVM patches have been merged).

2022-03-10 18:48 UTC, psteinfeld requested changes
Some nits, but things generally look good.

The build problem should be fixed, though.

2022-03-10 18:48 UTC, psteinfeld commented on flang/include/flang/Optimizer/CodeGen/CodeGen.h
> +  // operations that uses them at the LLVM level like fir.embox. Instead,
Should read "operations that use them".

2022-03-10 18:48 UTC, psteinfeld commented on flang/include/flang/Optimizer/CodeGen/CodeGen.h
> +  // that this programs would crash at runtime if the derived type descriptors
Should read "such programs" rather than "this programs".

2022-03-10 18:48 UTC, psteinfeld commented on flang/include/flang/Optimizer/CodeGen/CodeGen.h
> +  // are required by the runtime, so this only an option to help debugging.
Should read "this is only" rather than "this only".

2022-03-10 18:48 UTC, psteinfeld commented on flang/lib/Lower/Bridge.cpp
> +/// is required to described derived type to the runtime so that it can operate
Should read something like "required to describe the derived type" rather than "required to described type".

2022-03-10 18:48 UTC, psteinfeld commented on flang/lib/Lower/Bridge.cpp
> +  /// any region block. This is required because the FirOpBuilder assumes it is
Dis you mean to say "in a any region block"?

2022-03-10 18:48 UTC, psteinfeld commented on flang/lib/Lower/ConvertVariable.cpp
> +  // So far, use flags to detect if this symbols were generated during
I think you meant to say "if this symbol were" rather than if this symbols were".

2022-03-10 18:48 UTC, psteinfeld commented on flang/lib/Semantics/scope.cpp
> +bool Scope::IsKindParameterizedDerivedType() const {
The name of this function doesn't read quite right to me.  How about "IsDerivedTypeWithKindParameter"?

2022-03-10 18:48 UTC, psteinfeld commented on flang/lib/Semantics/runtime-type-info.cpp
> +      for (SymbolRef lenParam : *lenParameters) {
I get a build error on this line because the variable "lenParam" is not used.

2022-03-10 23:02 UTC, schweitzpgi commented
`linkonce` linkage is fine, but we'll want to use `linkonce_odr` to allow the backend to optimize these.

2022-03-10 23:23 UTC, schweitzpgi reviewed
Wow. Big change. Nice work, Jean!

2022-03-10 23:23 UTC, schweitzpgi commented on flang/include/flang/Optimizer/CodeGen/CodeGen.h
> +  bool ignoreMissingTypeDescriptors = false;
FWIW, FIR originally defined an Op to create a type descriptor, `fir.gentypedesc <type>`. This wasn't fully implemented, but it was intended to allow code gen to lazily create type descriptor information as needed.

That may be helpful to (1) discard type descriptor cruft that isn't really needed at compile-time, (2) create dummy type descriptors for testing that won't necessarily crash (like a nullptr), etc.

2022-03-10 23:23 UTC, schweitzpgi commented on flang/include/flang/Optimizer/Support/InternalNames.h
> +  static std::string getTypeDescriptorName(llvm::StringRef mangledTypeName);
The internal name is now harmonious through the compiler with recent changes to the front end, correct?

2022-03-10 23:23 UTC, schweitzpgi commented on flang/include/flang/Tools/CLOptions.inc
> +static llvm::cl::opt<bool> ignoreMissingTypeDescriptors(
You may want to consider if this needs to be exposed in the TA driver.

2022-03-10 23:23 UTC, schweitzpgi commented on flang/lib/Lower/Bridge.cpp
> +    // initializers have been generated.
Do you clean the cache after the globals are created?

2022-03-10 23:23 UTC, schweitzpgi commented on flang/lib/Lower/Bridge.cpp
> +  createGlobalOutsideOfAnyContext(const std::function<void()> &createGlobals) {
Doesn't creating the `fir::GlobalOp` and opening the building on that work? `GlobalOp` can have regions and entry blocks just like functions.

(This name is misleading. The bridge can't do anything at all without an MLIR context. Indeed, there is no such thing as "outside" that context. In fact, Globals have to be inside a ModuleOp or this is creating invalid IR.)

2022-03-10 23:23 UTC, schweitzpgi commented on flang/lib/Semantics/runtime-type-info.cpp
> +                ;
Is the dangling `;` needed?

2022-03-11 15:53 UTC, jeanPerier reviewed
> linkonce linkage is fine, but we'll want to use linkonce_odr to allow the backend to optimize these.

Done, that required adding some support for it in FIR.

Thanks @schweitzpgi and @psteinfeld for the detailed review, I have addressed all the comments. I will also upstream the updates in the LLVM parts.

2022-03-11 17:18 UTC, psteinfeld approved these changes

2022-03-11 17:19 UTC, psteinfeld commented
All builds and tests correctly and looks good.

2022-03-14 10:08 UTC, merged