[flang] Add some semantic checks for allocatable argument association
flang-compiler/f18-llvm-project pull request #1557
Opened 2022-03-30 06:34 UTC by PeixinQiao

If a dummy argument is allocatable, the associated actual argument
shall have deferred length parameter and must be one whole array, not
array section or substring. Currently programs not following this
get one crash during lowering or execution.

gfortran reports semantic errors for all the test cases and ifort reports semantic errors or has unexpected behaviors.

2022-03-30 09:10 UTC, jeanPerier requested changes
First of all, thanks for finding out that semantics is lacking a checks and that some lowering regression tests are none compliant here, and thanks for proposing a patch here.

Please move this patch for review in LLVM directly since it deals with semantics where the source of truth is LLVM main branch. You can update the bad lowering test that are not up streamed when cherry-picking this patch. 

The added checks are incorrect, they are rejecting valid programs and still accepting some bad programs. Also, it seems to me that the whole array part may reject valid passing of coindexed allocatables and is printing redundant error messages in some cases that where already caught.

I do not think Fortran standard requires actual arguments passed to allocatable to have deferred length parameters. What I read from Fortran 2018 15.5.2.5 point 4 is that the actual arguments length parameters must be deferred if and only if the related length parameter are deferred (I agree semantics is currently not enforcing this and it could).

Last point, is that the added check could be more generic: it also applies to POINTERs, and could be be done on parametrized derived type. It sounds fine to me if you leave out PDTs in a first patch, but I think POINTERs should be dealt with if ALLOCATABLEs are (the crashes you saw with bad programs would most likely occur with pointers).

2022-03-30 09:15 UTC, jeanPerier commented
> They are rejecting valid programs and still accepting some bad programs.
Here is an illustration of a valid program that your patch would reject:
```
  interface
    subroutine explicit(x)
      character(10), allocatable :: x(:)
    end subroutine
  end interface
  character(10), allocatable :: x(:)
  call explicit(x)
end
```
And here is an illustration of a bad program that your patch would still accept:
```
subroutine test(n)
  interface
    subroutine deferred_len(x)
      character(:), allocatable :: x(:)
    end subroutine
  end interface
  integer :: n
  character(n), allocatable :: x(:)
  call deferred_len(x)
end subroutine
```

2022-03-30 09:29 UTC, PeixinQiao commented on flang/lib/Semantics/check-call.cpp
> +    if (!evaluate::UnwrapWholeSymbolOrComponentDataRef(actual)) {
When I develop this code, I did it first. But considering there are some multiple error messages, I use the current version. If this is not preferred, I will combine them to report one error message.

2022-03-30 09:29 UTC, PeixinQiao commented on flang/test/Semantics/call05.f90
> +    !ERROR: ALLOCATABLE dummy argument 'a=' must be associated with an ALLOCATABLE actual argument and ALLOCATABLE actual argument cannot be array section or substring
Will fix this.

2022-03-30 09:29 UTC, PeixinQiao commented on flang/lib/Semantics/check-call.cpp
> +        !actualType.type().IsNonConstantLengthCharacter()) {
Right, I misunderstood. Will fix this.

2022-03-30 09:31 UTC, PeixinQiao commented on flang/test/Semantics/call06.f90
> +    call s04(cov[1])
You are right. I need remove this error message.

2022-03-30 09:36 UTC, PeixinQiao commented
> They are rejecting valid programs and still accepting some bad programs.
> Here is an illustration of a valid program that your patch would reject:
> ...
> And here is an illustration of a bad program that your patch would still accept:
> ...

Well, I didn't notice these. I think I need one function to check the length type parameter match to handle this case.

> Last point, is that the added check could be more generic: it also applies to POINTERs, and could be be done on parametrized derived type. It sounds fine to me if you leave out PDTs in a first patch, but I think POINTERs should be dealt with if ALLOCATABLEs are (the crashes you saw with bad programs would most likely occur with pointers).

For pointers, there is no such restrictions. I checked both gfortran and ifort, and current f18, passing array section and substring works fine for pointers. Maybe I missed some cases, but I prefer not to report error messages for pointers. I will leave PDTs later. Currently, I am not so familiar with how the PDTs works in F18, and don't get the test cases. These test cases are derived in classic-flang or workloads compiler by classic-flang.

All in all, I will fix all the above concerns and submit it in upstream.

2022-03-31 02:24 UTC, PeixinQiao commented
Updated in https://reviews.llvm.org/D122779.

2022-04-05 07:51 UTC, jeanPerier approved these changes
LGTM, thanks. Do you need me to merge the PR ?

2022-04-05 12:14 UTC, PeixinQiao commented
@jeanPerier Yes, please.

2022-04-05 14:29 UTC, merged